name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - hotfixes

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions on bin
        run: chmod +x bin/* || true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle install

      - name: Brakeman security scan
        run: |
          bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions on bin
        run: chmod +x bin/* || true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle install

      - name: JS vulnerability audit
        run: |
          bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions on bin
        run: chmod +x bin/* || true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle install


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install extra packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            google-chrome-stable \
            curl \
            libjemalloc2 \
            libvips \
            sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions on bin
        run: chmod +x bin/* || true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Install gems
        run: |
          rm -rf vendor/bundle
          bundle install

      - name: Create & migrate DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Prepare test DB
        run: |
          bundle exec rails db:test:prepare

      - name: Run Minitest
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test:all --verbose

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
